shell:
    - .alias
    - .env
    - .profile
    - .bash_profile
    - .bashrc
    - .zshenv
    - .zprofile
    - .zshrc
    - .config/fish/config.fish
tmux:
    - .tmux.conf
kitty:
    - .config/kitty/kitty.conf
ghostty:
    - .config/ghostty/config
alacritty:
    - .config/alacritty/alacritty.yml
iterm2:
    - Library/Preferences/com.googlecode.iterm2.plist
    - .config/iterm2/AppSupport/DynamicProfiles/
helix:
    - .config/helix/config.toml
    - .config/helix/languages.toml
vim:
    - .vimrc
    - .gvimrc
    - .vim/
neovim:
    - .config/nvim/
emacs:
    - .emacs
    - .emacs.d/
    - .config/emacs/
    - .config/doom/
    - .doom.d/
    - .spacemacs.d/
    - .spacemacs
vscode:
    - Library/Application Support/Code/User/settings.json
    - Library/Application Support/Code/User/keybindings.json
zed:
    - .config/zed/settings.json
yazi:
    - .config/yazi/yazi.toml
mackup:
    - .mackup.cfg
    - .mackup/
git:
    - .gitconfig
ssh:
    - .ssh/config
pip:
    - .config/pip/pip.conf
conda:
    - .condarc
npm:
    - .npmrc
#maven:
cargo:
    - .cargo/config.toml
orbstack:
    - .orbstack/config/docker.json
rime:
    - Library/Rime/
fcitx5:
    - .config/fcitx5/: .config/
    - .local/share/fcitx5/: .local/share/
hammerspoon:
    - .hammerspoon/init.lua
#raycast:
#karabiner:
mac-mouse-fix:
    - Library/Application Support/com.nuebling.mac-mouse-fix/config.plist
xgestures:
    - Library/Preferences/what.xGestures.plist
stats:
    - Library/Preferences/eu.exelban.Stats.plist
#firefox:
